### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by donl** [appy-one/acebase-server#15]
The following dependencies are missing by default and need to be manually installed after installing acebase-server.

swagger-jsdoc swagger-ui-express

**Comment by appy-one** [comment]
Those dependencies are only used in development environments and aren't installed if you use `npm install --production`

**Comment by appy-one** [comment]
I moved the dependencies from `devDependencies` to `dependencies` and published v1.10.1 to npm. Let me know if it works.
