### ISSUE TITLE
Extend server with custom route path (without /ext/[db name] prefix)

### ISSUE THREAD

**Issue by kbemcs** [appy-one/acebase-server#37]
It's not possible to extend the server with a path without prefix => It always has "/ext/[db name]" prefix.

**Comment by kbemcs** [comment]
i tried to completly remove the prefix in my fork https://github.com/kbemcs/acebase-server but somehow it doesn't worked :/

**Comment by appy-one** [comment]
You can use a server instance's `app` property to add custom routes:
```js
const server = new AceBaseServer(dbname, options);
server.app.get('/myroute', handler);
```
