### ISSUE TITLE
rules.json incorrect root path for .schema

### ISSUE THREAD

**Issue by donl** [appy-one/acebase-server#40]
When loading `.schema` rules from `rules.json`, the `path` being returned by the client using `db.schema.all()` are being prefixed with `/rules`

**Comment by appy-one** [comment]
Thanks for reporting, I'll look at it tomorrow!

**Comment by appy-one** [comment]
I found the culprit: https://github.com/appy-one/acebase-server/blob/dcdf9fd0cfdb57d7fecfb4c92519a8ed91e0981f/src/rules.ts#L111

This should be `accessRules.rules`
I'll publish a fix just now

**Comment by appy-one** [comment]
Hi Don, I published version 1.14.0 that should fix this!
Let me know if all works ok!
