### ISSUE TITLE
FR: add ability to use built-in authentication for custom routes 

### ISSUE THREAD

**Issue by donl** [appy-one/acebase-server#60]
Looking to be able to use the built-in authentication on endpoints created by `server.extend` and `server.app` to check if a request is from an authenticated user or not.

**Comment by appy-one** [comment]
You should be able to use `req.user` for this purpose. If the user is signed in, it will contain the user details, `null` otherwise.

**Comment by donl** [comment]
Ahh! That looks perfect!  Thanks
