### ISSUE TITLE
read/write rules undefined env values

### ISSUE THREAD

**Issue by donl** [appy-one/acebase-server#70]
When evaluating server rules, the variables ```data```, ```newData```, and ```root``` are undefined.

Is supporting any of these doable in the near future-- short of a full refactoring as mentioned in the source?

**Comment by appy-one** [comment]
I'll check if recent code changes made implementing this possible/easier

**Comment by appy-one** [comment]
Hi @donl I released this in v1.17.0 with updated docs. Note that the implementation is different from Firebase's, not less powerful though! Let me know if all works as expected

**Comment by donl** [comment]
Awesome! Looking forward to taking it for a spin!  Thanks
