### ISSUE TITLE
Restart server

### ISSUE THREAD

**Issue by srebling** [appy-one/acebase-server#77]
What is the proper way to programmatically stop and restart acebase-server? After running the code below, what commands are necessary to shutdown the server before running the same code again?

`        

        const { AceBaseServer } = require('acebase-server');
        const dbname = 'Messages';
        
        const settings = {
            path: './',
            host: 'localhost',
            port: 5757,
            authentication: {
                enabled: false,
                allowUserSignup: false,
                defaultAccessRule: 'allow',
                defaultAdminPassword: '75sdDSFg37w5'
            }
        }
        
        const server = new AceBaseServer(dbname, settings);
        server.on("ready", () => {
            console.log("SERVER ready");
        });
`

**Comment by appy-one** [comment]
First of all, my apologies for this late reply!
Run `server.shutdown()`

From the JSDocs:
```
shutdown(): void
Shuts down the server. Stops listening for incoming connections, breaks current connections and closes the database. Is automatically executed when a "SIGINT" process event is received.

Once the shutdown procedure is completed, it emits a "shutdown" event on the server instance, "acebase-server-shutdown" event on the process, and sends an 'acebase-server-shutdown' IPC message if Node.js clustering is used. These events can be handled by cluster managing code to kill or exit the process safely.
```
