### ISSUE TITLE
Dont see password in console

### ISSUE THREAD

**Issue by kodejuice** [appy-one/acebase-server#96]
![image](https://github.com/appy-one/acebase-server/assets/9017620/cd6a8d2d-39f9-4ede-a444-04a766d9611d)

<img width="1092" alt="image" src="https://github.com/appy-one/acebase-server/assets/9017620/4850c67d-6b81-4d44-bea8-ffb44bb157bb">

**Comment by appy-one** [comment]
The generated admin password is only displayed once upon db creation
